name       : mame
version    : '0.196'
release    : 3
source     :
    - https://github.com/mamedev/mame/archive/mame0196.tar.gz : fc4436a23d7f2ef0b3c3f600c00745bc468541d0d29bcd3a1e0c599c5c02df7f
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
    - MIT # 'console' and 'json' plugins
    - WTFPL # 'hiscore' plugin
    - CC0-1.0 # Localization files and other things
component  : games.emulator
summary    : Emulator for several hardware platforms to keep old games playable
description: |
    MAME's purpose is to preserve decades of software history. As electronic technology continues to rush forward, MAME prevents this important "vintage" software from being lost and forgotten. This is achieved by documenting the hardware and how it functions. The source code to MAME serves as this documentation. The fact that the software is usable serves primarily to validate the accuracy of the documentation (how else can you prove that you have recreated the hardware faithfully?).
    Over time, MAME absorbed the sister-project MESS (Multi Emulator Super System), so MAME now documents a wide variety of (mostly vintage) computers, video game consoles and calculators, in addition to the arcade video games that were its initial focus.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(flac)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(libjpeg)
    - pkgconfig(lua)
    - pkgconfig(portaudiocpp)
    - pkgconfig(Qt5Gui)
    - pkgconfig(RapidJSON)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(sqlite3)
    - pkgconfig(xinerama)
    - glm
    - portmidi-devel
    - pugixml-devel
build      : |
    # -g2 flag is removed because it's bloating mame64 executable file
    # AFAIK every 64-bit processor supports SSE2, so I'm enabling it
    # Using bundled asio and utf8proc libraries because they're not in Solus repository
    export CFLAGS=$(echo $CFLAGS | sed 's/-g2//')
    export CXXFLAGS=$(echo $CXXFLAGS | sed 's/-g2//')
    %make NOWERROR=1 \
          OPTIMIZE=2 \
          REGENIE=1 \
          SSE2=1 \
          TOOLS=0 \
          USE_SYSTEM_LIB_EXPAT=1 \
          USE_SYSTEM_LIB_FLAC=1 \
          USE_SYSTEM_LIB_GLM=1 \
          USE_SYSTEM_LIB_JPEG=1 \
          USE_SYSTEM_LIB_LUA=1 \
          USE_SYSTEM_LIB_PORTAUDIO=1 \
          USE_SYSTEM_LIB_PORTMIDI=1 \
          USE_SYSTEM_LIB_PUGIXML=1 \
          USE_SYSTEM_LIB_RAPIDJSON=1 \
          USE_SYSTEM_LIB_SQLITE3=1 \
          USE_SYSTEM_LIB_ZLIB=1

install    : |
    # Install executable files with proper filenames
    install -Dm00755 ./mame64 $installdir/usr/share/mame/mame
    install -Dm00755 $pkgfiles/mame $installdir/usr/bin/mame

    # File cleanup
    find . -name dir.txt -o \
           -name "LICENSE*" -o \
           -name *.po -o \
           -iname "readme*" | xargs rm -f
    rm -rf bgfx/shaders/{dx11,dx9,essl,metal}

    # Install data directories
    for folder_name in artwork bgfx ctrlr hash hlsl ini language plugins samples; do
        install -dm00755 $installdir/usr/share/mame/$folder_name
        cp -a $folder_name/* $installdir/usr/share/mame/$folder_name/
    done
    install -dm00755 $installdir/usr/share/mame/docs/swlist
    cp -a docs/swlist/* $installdir/usr/share/mame/docs/swlist/

    # Install manual
    install -dm00755 $installdir/usr/share/man/{man1,man6}
    for file in docs/man/*.1; do
        install -m00644 $file $installdir/usr/share/man/man1
    done
    for file in docs/man/*.6; do
        install -m00644 $file $installdir/usr/share/man/man6
    done

    # Copy config file
    install -m00644 $pkgfiles/mame.ini $installdir/usr/share/mame
