name       : mame
version    : '0.193'
release    : 2
source     :
    - https://github.com/mamedev/mame/archive/mame0193.tar.gz : 6b5e90b602befbcad2b6989b1e930d0ff6e537dc901f7b1615a3e6deec2207a2
license    :
    - GPL-2.0
    - BSD-3-Clause
    - MIT # 'console' and 'json' plugins
    - WTFPL # 'hiscore' plugin
    - CC0-1.0 # Localization files and other things
component  : games.emulator
summary    : Emulator for several hardware platforms to keep old games playable
description: |
    MAME's purpose is to preserve decades of software history. As electronic technology continues to rush
    forward, MAME prevents this important "vintage" software from being lost and forgotten. This is achieved
    by documenting the hardware and how it functions. The source code to MAME serves as this documentation.
    The fact that the software is usable serves primarily to validate the accuracy of the documentation
    (how else can you prove that you have recreated the hardware faithfully?). Over time, MAME absorbed the sister-project MESS
    (Multi Emulator Super System), so MAME now documents a wide variety of (mostly vintage) computers, video game consoles
    and calculators, in addition to the arcade video games that were its initial focus.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(flac)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(libjpeg)
    - pkgconfig(lua)
    - pkgconfig(portaudiocpp)
    - pkgconfig(Qt5Gui)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(sqlite3)
    - pkgconfig(xinerama)
    - portmidi-devel
build      : |
    # Remove -g2 flag because it's bloating mame64 executable file
    # AFAIK every 64-bit processor supports SSE2, so I'm enabling it
    # TODO: Use system utf8proc when it'll be available in repo
    export CFLAGS=$(echo $CFLAGS | sed 's/-g2//')
    export CXXFLAGS=$(echo $CXXFLAGS | sed 's/-g2//')
    %make USE_SYSTEM_LIB_ZLIB=1 \
          USE_SYSTEM_LIB_JPEG=1 \
          USE_SYSTEM_LIB_FLAC=1 \
          USE_SYSTEM_LIB_SQLITE3=1 \
          USE_SYSTEM_LIB_EXPAT=1 \
          USE_SYSTEM_LIB_PORTAUDIO=1 \
          USE_SYSTEM_LIB_PORTMIDI=1 \
          USE_SYSTEM_LIB_LUA=1 \
          OPTIMIZE=2 \
          TOOLS=0 \
          SSE2=1 \
          NOWERROR=1 \
          REGENIE=1 \
install    : |
    # Install executable files with proper filenames
    install -Dm00755 ./mame64 $installdir/usr/share/mame/mame
    install -Dm00755 $pkgfiles/mame $installdir/usr/bin/mame

    # File cleanup
    find . -name dir.txt -o \
           -name "LICENSE*" -o \
           -name *.po -o \
           -iname "readme*" | xargs rm -f
    rm -rf bgfx/shaders/{dx11,dx9,essl,metal}

    # Install data directories
    for folder_name in artwork bgfx ctrlr hash hlsl ini language plugins samples; do
        install -dm00755 $installdir/usr/share/mame/$folder_name
        cp -a $folder_name/* $installdir/usr/share/mame/$folder_name/
    done
    install -dm00755 $installdir/usr/share/mame/docs/swlist
    cp -a docs/swlist/* $installdir/usr/share/mame/docs/swlist/

    # Install manual
    install -dm00755 $installdir/usr/share/man/{man1,man6}
    for file in docs/man/*.1; do
        install -m00644 $file $installdir/usr/share/man/man1
    done
    for file in docs/man/*.6; do
        install -m00644 $file $installdir/usr/share/man/man6
    done

    # Copy config file
    install -m00644 $pkgfiles/mame.ini $installdir/usr/share/mame
